version: '3.8'

services:
  eth_bootnode:
    image: ethereum/client-go
    container_name: eth_bootnode
    volumes:
      - ./bootnode:/root/.ethereum
    command:
      - --datadir=/root/.ethereum
      - --networkid=123454321
      - --nat=extip:172.28.1.1
      - --nodekey=/root/.ethereum/boot.key
    networks:
      bridge_net:
        ipv4_address: 172.28.1.1

  eth_node1:
    image: ethereum/client-go
    container_name: eth_node1
    volumes:
      - ./node1:/root/.ethereum
    command:
      - --datadir=/root/.ethereum
      - --bootnodes=enode://6123065904a25a07f830543b284bd0e0dc669955811788a3556fa1b7dd09df009a7ce96e552a711f41738937bb362073e99af233a5510a5c07773e9ee6fdee07@172.28.1.1:30303
      - --networkid=123454321
      - --nat=extip:172.28.1.2
      - --unlock=0x129b9DAee478e7bc5edaDa471982E31FA7705622
      - --password=/root/.ethereum/password.txt
      - --mine
      - --miner.etherbase=0x129b9DAee478e7bc5edaDa471982E31FA7705622
    networks:
      bridge_net:
        ipv4_address: 172.28.1.2

  eth_node2:
    image: ethereum/client-go
    container_name: eth_node2
    ports:
      - 30303:30303
      - 30303:30303/udp
      - 8545:8545
      - 8546:8546
      - 8551:8551
    volumes:
      - ./node2:/root/.ethereum
    command:
      - --datadir=/root/.ethereum
      - --bootnodes=enode://6123065904a25a07f830543b284bd0e0dc669955811788a3556fa1b7dd09df009a7ce96e552a711f41738937bb362073e99af233a5510a5c07773e9ee6fdee07@172.28.1.1:30303
      - --networkid=123454321
      - --nat=extip:172.28.1.3
      - --http
      - --http.api=eth,net,web3,engine,admin
      - --http.addr=0.0.0.0
      - --http.vhosts=*
      - --http.corsdomain=*
      - --ws
      - --ws.origins=*
      - --ws.addr=0.0.0.0
      - --ws.api=eth,net,web3
      - --graphql
      - --graphql.corsdomain=*
      - --graphql.vhosts=*
      - --authrpc.addr=0.0.0.0
      - --authrpc.vhosts=*
      - --authrpc.jwtsecret=/root/.ethereum/jwt.hex
      - --authrpc.port=8551
      - --txlookuplimit=0
    networks:
      bridge_net:
        ipv4_address: 172.28.1.3

  # key derived from "//0"
  aleph_bootnode:
    image: aleph-node:latest
    container_name: aleph_bootnode
    volumes:
      - ./5D34dL5prEUaGNQtPPZ3yN5Y6BnkfXunKXXz6fo7ZJbLwRRH:/data
    environment:
      - PURGE_BEFORE_START=false
      - RUST_LOG=info
      - BASE_PATH=/data
      - CHAIN=/data/chainspec.json
      - NODE_KEY_PATH=/data/p2p_secret
      - ALLOW_PRIVATE_IPV4=true
      - DISCOVER_LOCAL=false
      - UNIT_CREATION_DELAY=300
      - RPC_PORT=9933
      - WS_PORT=9943
      - PORT=30333
      - VALIDATOR_PORT=30343
      - PUBLIC_VALIDATOR_ADDRESS=172.28.1.4:30343
      - PUBLIC_ADDR=/ip4/172.28.1.4/tcp/30333
      - NAME=AlephBootnode
      - BOOT_NODES=/ip4/127.28.1.4/tcp/30333/p2p/12D3KooWQpZTu9kBfD9jY4zyvhdi3MhtMGkofc6xZXNCTbo5dnfM
    networks:
      bridge_net:
        ipv4_address: 172.28.1.4

  # key derived from "//1"
  aleph_node1:
    image: aleph-node:latest
    container_name: aleph_node1
    # TODO: expose ports
    volumes:
      - ./5GBNeWRhZc2jXu7D55rBimKYDk8PGk8itRYFTPfC8RJLKG5o:/data
    environment:
      - PURGE_BEFORE_START=false
      - RUST_LOG=info
      - BASE_PATH=/data
      - CHAIN=/data/chainspec.json
      - NODE_KEY_PATH=/data/p2p_secret
      - ALLOW_PRIVATE_IPV4=true
      - DISCOVER_LOCAL=false
      - UNIT_CREATION_DELAY=300
      - RPC_PORT=9933
      - WS_PORT=9943
      - PORT=30333
      - VALIDATOR_PORT=30343
      - PUBLIC_VALIDATOR_ADDRESS=172.28.1.5:30343
      - PUBLIC_ADDR=/ip4/172.28.1.5/tcp/30333
      - NAME=AlephNode1
      - BOOT_NODES=/ip4/127.28.1.4/tcp/30333/p2p/12D3KooWQpZTu9kBfD9jY4zyvhdi3MhtMGkofc6xZXNCTbo5dnfM
    networks:
      bridge_net:
        ipv4_address: 172.28.1.5

# TODO : aleph_node2

networks:
  bridge_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
