version: '3.8'

services:
  bootnode:
    image: ethereum/client-go
    pull_policy: always
    container_name: bootnode
    volumes:
      - ./bootnode:/root/.ethereum
    command:
      - --datadir=/root/.ethereum
      - --networkid=123454321
      - --nat=extip:172.28.1.1
      - --nodekey=/root/.ethereum/boot.key
    networks:
      bridge_net:
        ipv4_address: 172.28.1.1

  node1:
    image: ethereum/client-go
    pull_policy: always
    container_name: node1
    volumes:
      - ./node1:/root/.ethereum
    command:
      - --datadir=/root/.ethereum
      - --bootnodes=enode://6123065904a25a07f830543b284bd0e0dc669955811788a3556fa1b7dd09df009a7ce96e552a711f41738937bb362073e99af233a5510a5c07773e9ee6fdee07@172.28.1.1:30303
      - --networkid=123454321
      - --nat=extip:172.28.1.2
      - --unlock=0x129b9DAee478e7bc5edaDa471982E31FA7705622
      - --password=/root/.ethereum/password.txt
      - --mine
      - --miner.etherbase=0x129b9DAee478e7bc5edaDa471982E31FA7705622
    networks:
      bridge_net:
        ipv4_address: 172.28.1.2

  node2:
    image: ethereum/client-go
    pull_policy: always
    container_name: node2
    ports:
      - 30303:30303
      - 30303:30303/udp
      - 8545:8545
      - 8546:8546
      - 8551:8551
    volumes:
      - ./node2:/root/.ethereum
    command:
      - --datadir=/root/.ethereum
      - --bootnodes=enode://6123065904a25a07f830543b284bd0e0dc669955811788a3556fa1b7dd09df009a7ce96e552a711f41738937bb362073e99af233a5510a5c07773e9ee6fdee07@172.28.1.1:30303
      - --networkid=123454321
      - --nat=extip:172.28.1.3
      - --http
      - --http.api=eth,net,web3,engine,admin
      - --http.addr=0.0.0.0
      - --http.vhosts=*
      - --http.corsdomain=*
      - --ws
      - --ws.origins=*
      - --ws.addr=0.0.0.0
      - --ws.api=eth,net,web3
      - --graphql
      - --graphql.corsdomain=*
      - --graphql.vhosts=*
      - --authrpc.addr=0.0.0.0
      - --authrpc.vhosts=*
      - --authrpc.jwtsecret=/root/.ethereum/jwt.hex
      - --authrpc.port=8551
      - --txlookuplimit=0
    networks:
      bridge_net:
        ipv4_address: 172.28.1.3

networks:
  bridge_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
