[package]
name = "e2e-tests"
version = "0.1.0"
edition = "2021"

[dependencies]
aleph_client = "3.0.0"
anyhow = "1.0.79"
clap = { version = "4.3.4", features = ["derive"] }
ethers = "2.0.9"
serde = "1.0.195"
serde_json = "1.0"
tokio = { version = "1.35.1", features = ["full"] }
