[package]
name = "e2e-tests"
version = "0.1.0"
edition = "2021"

[dependencies]
aleph_client = "3.0.0"
anyhow = "1.0.79"
clap = { version = "4.4.18", features = ["derive"] }
env_logger = "0.11.1"
ethers = "2.0.13"
log = "0.4.20"
serde = "1.0.196"
serde_json = "1.0"
subxt = "0.25.0"
tokio = { version = "1.35.1", features = ["full"] }
