version: '3.9'

services:
  # key derived from "//0"
  AlephBootnode:
    image: public.ecr.aws/p6e8q1z1/aleph-node:r-11.4
    container_name: aleph_bootnode
    user: "${UID}:${GID}"
    volumes:
      - ./5D34dL5prEUaGNQtPPZ3yN5Y6BnkfXunKXXz6fo7ZJbLwRRH:/data
    network_mode: host
    environment:
      - RPC_PORT=9933
      - WS_PORT=9943
      - PORT=30333
      - VALIDATOR_PORT=30343
      - PUBLIC_VALIDATOR_ADDRESS=127.0.0.1:30343
      - BOOT_NODES=/ip4/127.0.0.1/tcp/30333/p2p/12D3KooWF8rAsEhfqTKhbRnKwZdsX4ZRCapyPE3ttFLkMiv4Jyfe
      - PURGE_BEFORE_START=false
      - RUST_LOG=info
      - BASE_PATH=/data
      - CHAIN=/data/chainspec.json
      - NODE_KEY_PATH=/data/p2p_secret
      - ALLOW_PRIVATE_IPV4=true
      - DISCOVER_LOCAL=false
      - UNIT_CREATION_DELAY=500
      - NAME=AlephBootnode

  # key derived from "//1"
  AlephNode1:
    image: public.ecr.aws/p6e8q1z1/aleph-node:r-11.4
    container_name: aleph_node1
    volumes:
      - ./5GBNeWRhZc2jXu7D55rBimKYDk8PGk8itRYFTPfC8RJLKG5o:/data
    network_mode: host
    environment:
      - RPC_PORT=9934
      - WS_PORT=9944
      - PORT=30334
      - VALIDATOR_PORT=30344
      - PUBLIC_VALIDATOR_ADDRESS=127.0.0.1:30344
      - BOOT_NODES=/ip4/127.0.0.1/tcp/30333/p2p/12D3KooWF8rAsEhfqTKhbRnKwZdsX4ZRCapyPE3ttFLkMiv4Jyfe
      - PURGE_BEFORE_START=false
      - RUST_LOG=info
      - BASE_PATH=/data
      - CHAIN=/data/chainspec.json
      - NODE_KEY_PATH=/data/p2p_secret
      - ALLOW_PRIVATE_IPV4=true
      - DISCOVER_LOCAL=false
      - UNIT_CREATION_DELAY=500
      - NAME=AlephNode1

  # key derived from "//2"
  AlephNode2:
    image: public.ecr.aws/p6e8q1z1/aleph-node:r-11.4
    container_name: aleph_node2
    volumes:
      - ./5Dfis6XL8J2P6JHUnUtArnFWndn62SydeP8ee8sG2ky9nfm9:/data
    network_mode: host
    environment:
      - RPC_PORT=9935
      - WS_PORT=9945
      - PORT=30335
      - VALIDATOR_PORT=30345
      - PUBLIC_VALIDATOR_ADDRESS=127.0.0.1:30345
      - BOOT_NODES=/ip4/127.0.0.1/tcp/30333/p2p/12D3KooWF8rAsEhfqTKhbRnKwZdsX4ZRCapyPE3ttFLkMiv4Jyfe
      - PURGE_BEFORE_START=false
      - RUST_LOG=info
      - BASE_PATH=/data
      - CHAIN=/data/chainspec.json
      - NODE_KEY_PATH=/data/p2p_secret
      - ALLOW_PRIVATE_IPV4=true
      - DISCOVER_LOCAL=false
      - UNIT_CREATION_DELAY=500
      - NAME=AlephNode2

  Redis:
    image: redis:latest
    container_name: redis
    expose:
      - 6379
    ports:
      - 127.0.0.1:6379:6379
