[workspace]
members = ["relayer", "signer_client", "signer", "signer_tester"]
resolver = "2"

[workspace.dependencies]
aleph_client = { git = "https://github.com/Cardinal-Cryptography/aleph-node", rev = "r-13.2" }
ethers = { version = "2.0.9" }
subxt = { version = "0.30.1", features = ["substrate-compat"] }
tokio = { version = "1.36" }
tokio-util = { version = "0.7.10" }
tokio-vsock = { version = "0.5.0" }
