[package]
name = "relayer"
version = "0.1.0"
authors = ["fbielejec <filip.bielejec@cardinals.cc>"]
edition = "2021"

[dependencies]
env_logger = "0.10.0"
ethers = { version = "2.0.9", features = ["abigen", "rustls", "ws", "ethers-solc"] }
eyre = "0.6.8"
futures = "0.3.28"
log = "0.4.20"
rustc-hex = "2.1.0"
serde = "1.0.188"
serde_json = "1.0.105"
thiserror = "1.0.48"
tokio = { version = "1.32", features = ["rt", "rt-multi-thread", "macros", "test-util"] }

aleph_client = { path = "/home/filip/CloudStation/aleph/aleph-node/aleph-client" }
codec = { package = 'parity-scale-codec', version = "3.0.0", features = ['derive'] }
subxt = { version = "0.28.0", features = ["substrate-compat"] }
# contract-transcode = "2.1.0"
# ink_metadata = { version = "=4.0.1" }