[package]
name = "relayer"
version = "0.1.0"
authors = ["fbielejec <filip.bielejec@cardinals.cc>"]
edition = "2021"

[dependencies]
aleph_client = { git = "https://github.com/Cardinal-Cryptography/aleph-node", rev = "f637e2df9ecce892c6da5b2d8072b7e5cc8099d4" }
anyhow = "1.0.75"
clap = { version = "4.3.4", features = ["derive"] }
codec = { package = 'parity-scale-codec', version = "3.0.0", features = ['derive'] }
env_logger = "0.10.0"
ethers = { version = "2.0.9", features = ["abigen", "rustls", "ws", "ethers-solc"] }
eyre = "0.6.8"
futures = "0.3.28"
log = "0.4.20"
redis = { version = "*", features = ["tokio-comp", "aio"] }
rustc-hex = "2.1.0"
serde = "1.0.188"
serde_json = "1.0.105"
subxt = { version = "0.30.1", features = ["substrate-compat"] }
thiserror = "1.0.48"
tokio = { version = "1.32", features = ["rt", "rt-multi-thread", "macros", "test-util"] }