[package]
name = "relayer"
version = "0.1.0"
authors = ["fbielejec <filip.bielejec@cardinals.cc>"]
edition = "2021"

[dependencies]
env_logger = "0.10.0"
ethers = { version = "2.0.9", features = ["abigen", "rustls", "ws", "ethers-solc"] }
futures = "0.3.28"
serde = "1.0.188"
serde_json = "1.0.105"
log = "0.4.20"
thiserror = "1.0.48"
tokio = { version = "1.32", features = ["rt", "rt-multi-thread", "macros", "test-util"] }
eyre = "0.6.8"
rustc-hex = "2.1.0"
