---
services:
  Relayer1:
    container_name: most-relayer-1
    environment:
      - RELAYER_ID=1
      - DEV_MODE=true
      - RUST_LOG=info,aleph-client=warn
      - PAYOUT_ADDRESS=5GBNeWRhZc2jXu7D55rBimKYDk8PGk8itRYFTPfC8RJLKG5o
    image: most-relayer
    network_mode: host
    restart: on-failure:3
  Relayer2:
    container_name: most-relayer-2
    environment:
      - RELAYER_ID=2
      - DEV_MODE=true
      - RUST_LOG=info,aleph-client=warn
      - PAYOUT_ADDRESS=5Dfis6XL8J2P6JHUnUtArnFWndn62SydeP8ee8sG2ky9nfm9
    image: most-relayer
    network_mode: host
    restart: on-failure:3
  Relayer3:
    container_name: most-relayer-3
    environment:
      - RELAYER_ID=3
      - DEV_MODE=true
      - RUST_LOG=info,aleph-client=warn
      - PAYOUT_ADDRESS=5F4H97f7nQovyrbiq4ZetaaviNwThSVcFobcA5aGab6167dK
    image: most-relayer
    network_mode: host
    restart: on-failure:3
version: "3.9"
