---
name: Bridgenet - Re-create

on:
  workflow_dispatch:
    inputs:
      start:
        description: 'mainnet or testnet'
        required: true
        type: choice
        options:
          - testnet
          - mainnet
        default: testnet
  workflow_call:
    inputs:
      start:
        description: 'mainnet or testnet'
        required: true
        type: string

jobs:
  check-vars-and-secrets:
    name: Check vars and secrets
    uses: ./.github/workflows/_check-vars-and-secrets.yml
    secrets: inherit

  check-inputs:
    needs: [check-vars-and-secrets]
    name: Check inputs
    runs-on: ubuntu-20.04
    steps:
      - name: Validate inputs
        shell: bash
        run: |
          if [[ "${{ inputs.start }}" != "testnet" && "${{ inputs.start }}" != "mainnet" ]]; then
            echo "!!! Invalid start network"
            exit 1
          fi

  delete-bridgenet:
    needs: [check-inputs]
    name: Delete existing bridgenet
    # yamllint disable-line rule:line-length
    uses: Cardinal-Cryptography/github-actions/.github/workflows/_featurenet-delete.yml@v5
    secrets: inherit
    with:
      featurenet-name: updnet-bridgenet

  wait-for-deletion:
    needs: [delete-bridgenet]
    name: Delete existing bridgenet
    runs-on: [self-hosted, Linux, X64, small]
    steps:
      - name: Wait 3 minutes until all resources are removed
        shell: bash
        run: |
          echo "Waiting for 3 minutes until featurenet-watchman removes PVC's..."
          sleep 180

  create-bridgenet:
    needs: [wait-for-deletion]
    name: Create new bridgenet
    # yamllint disable-line rule:line-length
    uses: Cardinal-Cryptography/github-actions/.github/workflows/_featurenet-create.yml@v5
    secrets: inherit
    with:
      featurenet-name: bridgenet
      aleph-node-image: 'testnet'
      expiration: 'never'
      replicas: '5'
      internal: true
      delete-first: false
