---
name: Bridgenet - Re-create

on:
  workflow_dispatch:
    inputs:
      start:
        description: 'aleph-node image to be started'
        required: true
        type: choice
        options:
          - testnet
          - mainnet
        default: testnet
      destination:
        description: Node image tag, ie 7-byte SHA of some existing ECR aleph-node image tag
        required: true
        type: string
  workflow_call:
    inputs:
      start:
        description: 'aleph-node image to be started'
        required: true
        type: string
      destination:
        description: Node image tag, ie 7-byte SHA of some existing ECR aleph-node image tag
        required: true
        type: string

jobs:
  check-vars-and-secrets:
    name: Check vars and secrets
    uses: ./.github/workflows/_check-vars-and-secrets.yml
    secrets: inherit

  check-inputs:
    needs: [check-vars-and-secrets]
    name: Check inputs
    runs-on: ubuntu-20.04
    steps:
      - name: Validate inputs
        shell: bash
        run: |
          if [[ "${{ inputs.start }}" != "testnet" && "${{ inputs.start }}" != "mainnet" ]]; then
            echo "!!! Invalid start network"
            exit 1
          fi
          if [[
            "${{ inputs.destination }}" != "" && \
            ! "${{ inputs.destination }}" =~ ^[a-f0-9]{7}$
          ]]; then
            echo "!!! Expected a 7-byte SHA in destination parameter"
            exit 1
          fi

  delete-bridgenet:
    needs: [check-inputs]
    name: Delete existing bridgenet
    # yamllint disable-line rule:line-length
    uses: Cardinal-Cryptography/github-actions/.github/workflows/_featurenet-delete.yml@v3
    secrets: inherit
    with:
      featurenet-name: updnet-bridgenet

  wait-for-deletion:
    needs: [delete-bridgenet]
    name: Delete existing bridgenet
    runs-on: [self-hosted, Linux, X64, small]
    steps:
      - name: Wait 3 minutes until all resources are removed
        shell: bash
        run: |
          echo "Waiting for 3 minutes until featurenet-watchman removes PVC's..."
          sleep 180

  create-bridgenet:
    needs: [wait-for-deletion]
    name: Create new bridgenet
    # yamllint disable-line rule:line-length
    uses: Cardinal-Cryptography/github-actions/.github/workflows/_featurenet-create-from-net.yml@v3
    secrets: inherit
    with:
      featurenet-name: updnet-bridgenet
      start: 'mainnet'
      expiration: 'never'
      replicas: '5'
      internal: true

  update-bridgenet:
    needs: [create-bridgenet]
    name: Update new bridgenet
    # yamllint disable-line rule:line-length
    uses: Cardinal-Cryptography/github-actions/.github/workflows/_featurenet-update.yml@v3
    secrets: inherit
    with:
      featurenet-name: updnet-bridgenet
      destination: ${{ inputs.destination }}
      rolling-update-partition: '0'
      replicas: '5'
      internal: true
