---
name: Bridgenet - Update

on:
  workflow_dispatch:
    inputs:
      aleph-node-image:
        description: Node image tag, ie 7-byte SHA of some existing ECR aleph-node image tag
        required: true
        type: string
  workflow_call:
    inputs:
      aleph-node-image:
        description: Node image tag, ie 7-byte SHA of some existing ECR aleph-node image tag
        required: true
        type: string

jobs:
  check-vars-and-secrets:
    name: Check vars and secrets
    uses: ./.github/workflows/_check-vars-and-secrets.yml
    secrets: inherit

  check-inputs:
    name: Check inputs
    runs-on: ubuntu-20.04
    steps:
      - name: Validate inputs
        shell: bash
        run: |
          if [[ ! '${{ inputs.aleph-node-image }}' =~ ^[a-z0-9][a-z0-9\._\-]{1,48}$ ]]; then
            echo "!!! Invalid aleph-node image"
            exit 1
          fi

  update-bridgenet:
    needs: [check-inputs]
    name: Update new bridgenet
    # yamllint disable-line rule:line-length
    uses: Cardinal-Cryptography/github-actions/.github/workflows/_featurenet-create.yml@v5
    secrets: inherit
    with:
      featurenet-name: updnet-bridgenet
      aleph-node-image: ${{ inputs.aleph-node-image }}
      rolling-update-partition: '0'
      expiration: 'never'
      replicas: '5'
      internal: true
