---
name: Bridgenet - Update

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'git ref: full commit hash, branch, tag'
        required: true
        type: string

jobs:
  check-vars-and-secrets:
    name: Check vars and secrets
    uses: ./.github/workflows/_check-vars-and-secrets.yml
    secrets: inherit

  check-inputs:
    name: Check inputs
    runs-on: ubuntu-20.04
    steps:
      - name: Validate inputs
        shell: bash
        run: |
          if [[ ! '${{ inputs.ref }}' =~ ^[a-z0-9][a-z0-9\._\-]{1,48}$ ]]; then
            echo "!!! Invalid aleph-node image"
            exit 1
          fi

  get-full-docker-image-path-from-ref:
    name: Get full aleph-node full docker path path for ref
    needs: [check-inputs]
    runs-on: ubuntu-20.04
    outputs:
      fqdn-image: ${{ steps.get-aleph-node-fqdn-image.outputs.fqdn-image }}
      ref: ${{ steps.get-aleph-node-fqdn-image.outputs.ref }}
      image-exists: ${{ steps.get-aleph-node-fqdn-image.outputs.image-exists }}
    steps:
      - name: Get aleph-node fqdn path
        id: get-aleph-node-fqdn-image
        uses: Cardinal-Cryptography/github-actions/get-aleph-node-fqdn-image@v6
        with:
          ref: ${{ inputs.ref }}
          test-binary: 'false'
          ecr-dev-node-repo: ${{ vars.ECR_DEV_ALEPH_NODE_REPO }}
          ecr-prod-node-repo: ${{ vars.ECR_ALEPH_NODE_REPO }}

  fail-when-image-not-exists:
    name: Fail when image does not exist
    needs: [get-full-docker-image-path-main-branch]
    if: ${{ needs.get-full-docker-image-path-main-branch.outputs.image-exists != 'true' }}
    runs-on: ubuntu-20.04
    steps:
      - name: Exit 1
        run: |
          echo "Aleph-node image '${{ needs.get-full-docker-image-path-main-branch.outputs.fqdn-image }}' does not exist"
          exit 1

  update-bridgenet:
    needs: [get-full-docker-image-path-main-branch]
    if: ${{ needs.get-full-docker-image-path-main-branch.outputs.image-exists == 'true' }}
    name: Update new bridgenet
    # yamllint disable-line rule:line-length
    uses: Cardinal-Cryptography/github-actions/.github/workflows/_featurenet-create.yml@v6
    secrets: inherit
    with:
      featurenet-name: updnet-bridgenet
      aleph-node-image: ${{ needs.get-full-docker-image-path-main-branch.outputs.fqdn-image }}
      rolling-update-partition: '0'
      expiration: 'never'
      internal: true
