---
name: Bridgenet - Re-create

on:
  workflow_dispatch:
    inputs:
      start:
        description: 'aleph-node image to be started'
        required: true
        type: choice
        options:
          - testnet
          - mainnet
        default: testnet
      destination:
        description: Node image tag, ie 7-byte SHA of some existing ECR aleph-node image tag
        required: true
        type: string
  workflow_call:
    inputs:
      start:
        description: 'aleph-node image to be started'
        required: true
        type: string
      destination:
        description: Node image tag, ie 7-byte SHA of some existing ECR aleph-node image tag
        required: true
        type: string

jobs:
  check-inputs:
    name: Check inputs
    runs-on: ubuntu-20.04
    steps:
      - name: Validate inputs
        shell: bash
        run: |
          if [[ "${{ inputs.start }}" != "testnet" && "${{ inputs.start }}" != "mainnet" ]]; then
            echo "!!! Invalid start network"
            exit 1
          fi
          if [[
            "${{ inputs.destination }}" != "" && \
            ! "${{ inputs.destination }}" =~ ^[a-f0-9]{7}$
          ]]; then
            echo "!!! Expected a 7-byte SHA in destination parameter"
            exit 1
          fi

  delete-bridgenet:
    needs: [check-inputs]
    name: Delete existing bridgenet
    runs-on: [self-hosted, Linux, X64, small]
    steps:
      - name: Delete bridgenet app and data
        uses: Cardinal-Cryptography/github-actions/delete-featurenet@v2
        with:
          gh-ci-token: ${{ secrets.CI_GH_TOKEN }}
          aws-access-key-id: ${{ secrets.AWS_DEVNET_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEVNET_SECRET_ACCESS_KEY }}
          ecr-public-registry: ${{ vars.ECR_PUBLIC_REGISTRY }}
          argo-sync-user-token: ${{ secrets.ARGO_SYNC_USER_TOKEN }}
          repo-featurenets-name: ${{ secrets.REPO_OPS_FEATURENETS_NAME }}
          repo-featurenet-template-name: ${{ secrets.REPO_FEATURENET_TEMPLATE_NAME }}
          argo-host: ${{ secrets.ARGOCD_DEVNET_HOST }}
          featurenet-keys-s3bucket-name: ${{ secrets.FEATURENET_KEYS_S3BUCKET_NAME }}
          featurenet-name: updnet-bridgenet
          git-commit-author: ${{ secrets.AUTOCOMMIT_AUTHOR }}
          git-commit-email: ${{ secrets.AUTOCOMMIT_EMAIL }}

      - name: Wait 3 minutes until all resources are removed
        shell: bash
        run: |
          echo "Waiting for 5 minutes until featurenet-watchman removes PVC's..."
          sleep 180

  create-bridgenet:
    needs: [delete-bridgenet]
    name: Create new bridgenet
    runs-on: [self-hosted, Linux, X64, small]
    steps:
      - name: Start bridgenet Deployment
        uses: bobheadxi/deployments@v1.1.0
        id: deployment
        with:
          step: start
          token: ${{ secrets.CI_GH_TOKEN }}
          env: updnet-bridgenet
          override: true
          debug: true

      - name: Create bridgenet from scratch, node binary from testnet or mainnet
        uses: Cardinal-Cryptography/github-actions/create-featurenet@v2
        id: create-featurenet
        with:
          gh-ci-token: ${{ secrets.CI_GH_TOKEN }}
          argo-sync-user-token: ${{ secrets.ARGO_SYNC_USER_TOKEN }}
          repo-featurenets-name: ${{ secrets.REPO_OPS_FEATURENETS_NAME }}
          repo-featurenet-template-name: ${{ secrets.REPO_FEATURENET_TEMPLATE_NAME }}
          argo-host: ${{ secrets.ARGOCD_DEVNET_HOST }}
          ecr-public-registry: ${{ vars.ECR_PUBLIC_REGISTRY }}
          featurenet-keys-s3bucket-name: ${{ secrets.FEATURENET_KEYS_S3BUCKET_NAME }}
          featurenet-name: updnet-bridgenet
          featurenet-aleph-node-image: ${{ inputs.start == 'mainnet' && 'mainnet' || 'testnet' }}
          expiration: '999999h'
          replicas: '5'
          internal: 'true'
          git-commit-author: ${{ secrets.AUTOCOMMIT_AUTHOR }}
          git-commit-email: ${{ secrets.AUTOCOMMIT_EMAIL }}
          wait-for-finalized-heads: "true"

      - name: Finish bridgenet Deployment
        uses: bobheadxi/deployments@v1
        if: always()
        with:
          step: finish
          token: ${{ secrets.CI_GH_TOKEN }}
          status: ${{ job.status }}
          env: updnet-bridgenet
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          # yamllint disable-line rule:line-length
          env_url: https://dev.azero.dev/?rpc=wss%3A%2F%2F${{ steps.create-featurenet.outputs.ws-hostname }}#/explorer
          debug: true

  update-bridgenet:
    needs: [create-bridgenet]
    name: Update new bridgenet
    runs-on: [self-hosted, Linux, X64, small]
    steps:
      - name: Start bridgenet Deployment
        uses: bobheadxi/deployments@v1.1.0
        id: deployment
        with:
          step: start
          token: ${{ secrets.CI_GH_TOKEN }}
          env: updnet-bridgenet
          override: true

      - name: Update bridgenet data, app and deploy it
        uses: Cardinal-Cryptography/github-actions/create-featurenet@v2
        id: create-featurenet
        with:
          gh-ci-token: ${{ secrets.CI_GH_TOKEN }}
          argo-sync-user-token: ${{ secrets.ARGO_SYNC_USER_TOKEN }}
          repo-featurenets-name: ${{ secrets.REPO_OPS_FEATURENETS_NAME }}
          repo-featurenet-template-name: ${{ secrets.REPO_FEATURENET_TEMPLATE_NAME }}
          argo-host: ${{ secrets.ARGOCD_DEVNET_HOST }}
          ecr-public-registry: ${{ vars.ECR_PUBLIC_REGISTRY }}
          featurenet-keys-s3bucket-name: ${{ secrets.FEATURENET_KEYS_S3BUCKET_NAME }}
          featurenet-name: updnet-bridgenet
          featurenet-aleph-node-image: ${{ inputs.destination }}
          rolling-update-partition: '0'
          replicas: '5'
          internal: 'true'
          git-commit-author: ${{ secrets.AUTOCOMMIT_AUTHOR }}
          git-commit-email: ${{ secrets.AUTOCOMMIT_EMAIL }}
          hard-refresh: 'true'
          wait-for-finalized-heads: "true"

      - name: Finish updatenet Deployment
        uses: bobheadxi/deployments@v1
        if: always()
        with:
          step: finish
          token: ${{ secrets.CI_GH_TOKEN }}
          status: ${{ job.status }}
          env: updnet-bridgenet
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          # yamllint disable-line rule:line-length
          env_url: https://dev.azero.dev/?rpc=wss%3A%2F%2F${{ steps.create-featurenet.outputs.ws-hostname }}#/explorer
