
name: Check formatting

on:
  pull_request:
    branches:
    - master
    - 'release-*'
  push:
    branches:
    - master
    - 'release-*'

jobs:
  test:
    name: Check formatting
    runs-on: [self-hosted, Linux, X64, large]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Install Rust toolchain"
        uses: Cardinal-Cryptography/github-actions/install-rust-toolchain@v6

      - name: Check code formatting
        shell: bash
        run: make format-check
