---
name: Bridgenet - deploy contracts

on:
  push:
    branches:
      - master
      - kz/deployment-with-setup

jobs:
  test-azero-contracts:
    uses: ./.github/workflows/test-azero-contracts.yml

  test-eth-contracts:
    uses: ./.github/workflows/test-eth-contracts.yml

  deploy-contracts:
    name: Deploy and setup contracts
    runs-on: self-hosted
    needs: [test-eth-contracts, test-azero-contracts]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: asdf-vm/actions/install@v2

      - name: Deploy eth contracts
        shell: bash
        run: make deploy-eth NETWORK=bridgenet

      - name: Deploy and setup azero contracts
        shell: bash
        run: AZERO_ENV=bridgenet make deploy-azero-docker

      - name: Setup eth contracts
        shell: bash
        run: make setup-eth NETWORK=bridgenet

      - uses: actions/upload-artifact@v4
        with:
          name: eth-artifacts
          if-no-files-found: error
          retention-days: 1
          path: |
            eth/artifacts
            eth/addresses.json

      - uses: actions/upload-artifact@v4
        with:
          name: azero-artifacts
          if-no-files-found: error
          retention-days: 1
          path: |
            azero/artifacts
            azero/addresses.json

  upload-contract-artifacts:
    name: Upload contract artifacts to S3
    runs-on: self-hosted
    needs: [deploy-contracts]
    strategy:
      matrix:
        include:
          - from: contract_spec.json
            to: addresses/fe_bridgenet
            filname: bridgenet.json
          - from: eth/artifacts/contracts/Governance.sol/Governance.json
            to: contracts/${{ github.sha }}/eth_governace
          - from: eth/artifacts/contracts/Most.sol/Most.json
            to: contracts/${{ github.sha }}/eth_most
          - from: eth/artifacts/contracts/Token.sol/Token.json
            to: contracts/${{ github.sha }}/eth_token
          - from: eth/artifacts/contracts/WETH9.sol/WETH9.json
            to: contracts/${{ github.sha }}/eth_weth9
          - from: azero/artifacts/most.json
            to: contracts/${{ github.sha }}/azero_most
          - from: azero/artifacts/most.contract
            to: contracts/${{ github.sha }}/azero_most
          - from: azero/artifacts/governance.json
            to: contracts/${{ github.sha }}/azero_governance
          - from: azero/artifacts/governance.contract
            to: contracts/${{ github.sha }}/azero_governance
          - from: azero/artifacts/token.json
            to: contracts/${{ github.sha }}/azero_token
          - from: azero/artifacts/token.contract
            to: contracts/${{ github.sha }}/azero_token

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v4
        with:
          name: azero-artifacts
          path: azero

      - uses: actions/download-artifact@v4
        with:
          name: eth-artifacts
          path: eth

      - name: Prepare contract_spec.json
        shell: bash
        run: make contract_spec.json

      - name: Copy files to S3 AWS bucket
        uses: Cardinal-Cryptography/github-actions/copy-file-to-s3@v1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEVNET_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEVNET_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-central-1
        with:
          compression: false
          source-path: ${{ matrix.from }}
          s3-bucket-filename: ${{ matrix.filename }}
          s3-bucket-path: most/${{ matrix.to }}
          s3-bucket-name: alephzero-devnet-contracts-test
