name: Devnet eth nodes - Re-create

on:
  workflow_dispatch:

concurrency:
  group: "${{ github.ref }}-${{ github.workflow }}"
  cancel-in-progress: false

jobs:
  check-vars-and-secrets:
    name: Check vars and secrets
    uses: ./.github/workflows/_check-vars-and-secrets.yml
    secrets: inherit

  recreate-eth:
    needs: [check-vars-and-secrets]
    name: Re-create eth nodes
    runs-on: [self-hosted, Linux, X64, small]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3.2
        with:
          version: 'v1.23.6'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        env:
          AWS_REGION: eu-central-1
        with:
          aws-access-key-id: ${{ secrets.AWS_DEVNET_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEVNET_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Scale replicas to 0 and remove PVC's
        shell: bash
        env:
          K8S_NAMESPACE: bridge
        run: |
          aws eks --region eu-central-1 update-kubeconfig --name alephzero-devnet-eu-central-1-eks

          kubectl scale --replicas=0 statefulset/eth -n ${{ env.K8S_NAMESPACE }}
          kubectl delete pvc -l app=eth -n ${{ env.K8S_NAMESPACE }} --ignore-not-found=true
          sleep 10

      - name: Scale replicas back to 1
        shell: bash
        env:
          K8S_NAMESPACE: bridge
        run: |
          kubectl scale --replicas=1 statefulset/eth -n ${{ env.K8S_NAMESPACE }}
          sleep 10
