
name: Lint code

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  test:
    name: Lint code
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lint code
        shell: bash
        run: make lint
