---
name: Master branch commit

on:
  push:
    branches:
      - master
      - add-building-common-contract

jobs:
  check-vars-and-secrets:
    name: Check vars and secrets
    uses: ./.github/workflows/_check-vars-and-secrets.yml
    secrets: inherit

  compile-contracts-and-deploy-to-bridgenet:
    needs: [check-vars-and-secrets]
    name: Compile contracts and deploy to bridgenet
    uses: ./.github/workflows/contracts-compile-and-deploy-to-bridgenet.yml
    secrets: inherit

  compile-common-contracts:
    needs: [compile-contracts-and-deploy-to-bridgenet]
    name: Compile and store common contracts
    uses: ./.github/workflows/common-contracts-compile-and-store.yml
    secrets: inherit

  build-and-deploy-relayer-to-devnet:
    needs: [compile-common-contracts]
    name: Build and deploy relayer to devnet
    uses: ./.github/workflows/relayer-build-and-deploy-to-devnet.yml
    secrets: inherit
