---
name: Master branch commit

on:
  push:
    branches:
      - master

jobs:
  check-vars-and-secrets:
    name: Check vars and secrets
    uses: ./.github/workflows/_check-vars-and-secrets.yml
    secrets: inherit

  compile-contracts-and-deploy-to-testnet:
    needs: [check-vars-and-secrets]
    name: Compile contracts and deploy to bridgenet
    uses: ./.github/workflows/contracts-compile-and-deploy-to-testnet.yml
    secrets: inherit
