---
name: Master branch commit

on:
  push:
    branches:
      - master
      - MOST-192

jobs:
  check-vars-and-secrets:
    name: Check vars and secrets
    uses: ./.github/workflows/_check-vars-and-secrets.yml
    secrets: inherit

#  test-azero-contracts:
#    needs: [check-vars-and-secrets]
#    uses: ./.github/workflows/test-azero-contracts.yml
#
#  test-eth-contracts:
#    needs: [check-vars-and-secrets]
#    uses: ./.github/workflows/test-eth-contracts.yml

  compile-contracts-and-deploy-to-devenv:
    #needs: [test-azero-contracts, test-eth-contracts]
    name: Compile contracts and deploy to devenv
    uses: ./.github/workflows/contracts-compile-and-deploy-to-devenv.yml
    secrets: inherit

  build-l1-relayer:
    needs: [compile-contracts-and-deploy-to-devenv]
    name: Build L1 relayer
    uses: ./.github/workflows/l1-relayer-build.yml
    secrets: inherit

  build-l2-relayer:
    needs: [compile-contracts-and-deploy-to-devenv]
    name: Build L2 relayer
    uses: ./.github/workflows/l2-relayer-build.yml
    secrets: inherit
