# Runs unit tests for the relayer

name: Relayer tests

on:
  pull_request:
    branches:
    - master
    - 'release-*'
  push:
    branches:
    - master
    - 'release-*'
  workflow_call:

jobs:
  test:
    name: Test relayer
    runs-on: [self-hosted, Linux, X64, large]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Install Rust toolchain"
        uses: Cardinal-Cryptography/github-actions/install-rust-toolchain@v6

      - name: Run tests
        shell: bash
        run: |
          make test-relayer
          make test-relayer-l2
