# Runs unit tests for the relayer

name: Relayer tests

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
  workflow_call:

jobs:
  test:
    name: Test relayer
    runs-on: [self-hosted, Linux, X64, large]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: "Install Rust toolchain"
        uses: Cardinal-Cryptography/aleph-node/.github/actions/install-rust-toolchain@5eda3cd85e7e3aec3f2db7a26631c65d52c4b9ea

      - name: Run tests
        shell: bash
        run: make test-relayer
