# Runs bridge and perform transfers from and to ethereum.

name: Transfer test

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      environment:
        description: Environment in which the test should be executed
        default: 'local'
        required: false
        type: string

jobs:
  test:
    name: Test transfers
    runs-on: [self-hosted, Linux, X64, large]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Install Rust toolchain"
        uses: Cardinal-Cryptography/github-actions/install-rust-toolchain@v6
