# Runs bridge and perform transfers from and to ethereum.

name: Transfer test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_call:

jobs:
  test:
    name: Test transfers
    runs-on: [self-hosted, Linux, X64, large]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Install Rust toolchain"
        uses: Cardinal-Cryptography/github-actions/install-rust-toolchain@v6

      - name: Run tests
        shell: bash
        run: |
          make local-bridgenet
          sleep 60 # wait 1 minute for everything to be runing
          make deploy run-relayers
          
          make ethereum-azero-transfer
          sleep 300 # wait 5 minutes for transfer to register on both chains
          make azero-ethereum-transfer