---
name: tmp test new contracts gh actions

on:
  push:
    branches:
      - A0-4026-change-workflows-to-use-new-actions-for-contracts

jobs:
  main:
    name: test new actions
    runs-on: [self-hosted, Linux, X64, small]
    steps:
      - name: create dummy files
        shell: bash
        run: |
          echo 'bofh' > contract_spec.json
          mkdir -p some/artifact
          echo 'bofh2' > some/artifact/Artifact.json

      - name: store contract addresses on s3 bucket
        uses: Cardinal-Cryptography/github-actions/store-contract-addresses@A0-4026-add-code-for-dealing-with-contracts
        with:
          aws-access-key-id: ${{ secrets.CONTRACTS_MOST_ADDRESSES_BRIDGENET_DEV_RW_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CONTRACTS_MOST_ADDRESSES_BRIDGENET_DEV_RW_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.CONTRACTS_S3BUCKET_REGION }}
          s3-bucket: ${{ secrets.CONTRACTS_S3BUCKET_NAME }}
          src-addresses: contract_spec.json
          project: most
          chain-environment: bridgenet
          frontend-environment: mikotest
          if-exist: skip

      - name: store contract artifacts on s3 bucket
        uses: Cardinal-Cryptography/github-actions/store-contract-artifact@A0-4026-add-code-for-dealing-with-contracts
        with:
          aws-access-key-id: ${{ secrets.CONTRACTS_MOST_ARTIFACTS_RW_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CONTRACTS_MOST_ARTIFACTS_RW_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.CONTRACTS_S3BUCKET_REGION }}
          s3-bucket: ${{ secrets.CONTRACTS_S3BUCKET_NAME }}
          src-artifact: some/artifact/Artifact.json
          project: most
          version: mikotest
          contract: azero_artifact
          if-exist: skip

      - name: download contract addresses from s3 bucket
        uses: Cardinal-Cryptography/github-actions/download-contract-addresses@A0-4026-add-code-for-dealing-with-contracts
        with:
          aws-access-key-id: ${{ secrets.CONTRACTS_MOST_ADDRESSES_BRIDGENET_DEV_RW_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CONTRACTS_MOST_ADDRESSES_BRIDGENET_DEV_RW_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.CONTRACTS_S3BUCKET_REGION }}
          s3-bucket: ${{ secrets.CONTRACTS_S3BUCKET_NAME }}
          dst-addresses: downloaded-addresses.json
          project: most
          chain-environment: bridgenet
          frontend-environment: mikotest

      - name: download contract artifact from s3 bucket
        uses: Cardinal-Cryptography/github-actions/download-contract-addresses@A0-4026-add-code-for-dealing-with-contracts
        with:
          aws-access-key-id: ${{ secrets.CONTRACTS_MOST_ADDRESSES_BRIDGENET_DEV_RW_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CONTRACTS_MOST_ADDRESSES_BRIDGENET_DEV_RW_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.CONTRACTS_S3BUCKET_REGION }}
          s3-bucket: ${{ secrets.CONTRACTS_S3BUCKET_NAME }}
          dst-artifact: downloaded_azero_most
          project: most
          version: f8ef61786c5cad7197cb8a030f334827b3f81f8d
          contract: azero_most

      - name: list files
        shell: bash
        run: |
          ls -al
          find downloaded_azero_most
